# Generated by Django 3.2.6 on 2021-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('invite_url', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
    ]
